name: Run once at 1:40 AM IST on May 26, 2025

on:
  schedule:
    - cron: '10 20 25 5 *'  # This means May 25 20:10 UTC = May 26 1:40 IST
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run checkin script
        env:
          email: ${{ secrets.email }}
          password: ${{ secrets.password }}
        run: python main.py checkin
